version: 2
updates:
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /desktop/src-tauri
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
